version: '3.8'

services:

  web:
    env_file:
      - .env
    build: .
    ports:
      - "8000:8000"
    command: gunicorn --bind 0.0.0.0 -w 4 -k uvicorn.workers.UvicornWorker main:app
#    command: uvicorn main:app --host 0.0.0.0 --port 9000 --reload
    volumes:
     - .:/usr/src/app
