version: '3.8'

services:

  web:
    env_file:
      - .env
    build: .
    ports:
      - "9000:9000"
    command: uvicorn main:app --host 0.0.0.0 --port 9000 --reload
    volumes:
     - .:/usr/src/app
